### ISSUE TITLE
import FloatLabels from 'float-labels.js' doesn't seem to import

### ISSUE THREAD

**Issue by oshihirii** [geminilabs/float-labels.js#45]
Hello,

I believe import functionality has been implemented, see:  https://github.com/pryley/float-labels.js/issues/21.  

However, it doesn't seem to be importing for me.  

Webpack build doesn't throw errors, but no plugin classes are added to the label etc.  

**Install**
```
npm install float-labels.js --save
```
**my_entry_file.js**
```js
import FloatLabels from 'float-labels.js';

$(document).ready(function() {
var floatlabels = new FloatLabels( '#input_1', {
// options go here
});
}); 

```
**index.html**
```html
<label for="input_1">some text here</label>
<textarea id="input_1" class="uk-textarea" rows="4" placeholder="some text here"></textarea>

<label for="input_2">some text here</label>
<textarea id="input_2" class="uk-textarea" rows="4" placeholder="some text here"></textarea>
```

**Version**
```
"float-labels.js": "^3.3.9"
```

Thank You.

**Comment by oshihirii** [comment]
Beg my pardon, the class `fl-form` *is* being added to the textarea element, I was expecting it to be added to the label element.  

But functionality does not seem to be working - do I need to import the relevant css manually, or link to it in index.html?

**Comment by oshihirii** [comment]
Hmm, I had to wrap my elements in `<form>` tags and instantiate like this:

```js
var floatlabels = new FloatLabels('form', {
    // see:  https://github.com/pryley/float-labels.js#options
    customEvent: null,
    customLabel: null,
    customPlaceholder: null,
    exclude: '.no-label',
    inputRegex: /email|number|password|search|tel|text|url/,
    prefix: 'fl-',
    prioritize: 'label',
    requiredClass: 'required',
    style: 0,
    transform: 'input, select, textarea',
});
```

and also had to copy the css file from plugin dist folder to my app css folder and add the following to index.html `<head>`:

```html
<link href="css/float-labels.css" rel="stylesheet">
```
And for reference, I just used the following CSS to preserve the existing styles of my form:

```css
/*!
 * Float Labels
 * @version: 3.3.9
 * @author: Paul Ryley (http://geminilabs.io)
 * @url: https://pryley.github.io/float-labels.js
 * @license: MIT
 */

/* customised to just use required styles */  
.fl-form .fl-wrap {
  position: relative;
}

.fl-form label.fl-label {
  opacity: 0;
  visibility: hidden;
  display: block;
  position: absolute;
  top: -15px;
  left: 0;
  font-size: 12px;
  font-weight: 400;
  line-height: 1;
  color: #8d8d8d;
  transition: all 0.2s ease-in-out;
  z-index: 1;
  font-family: 'Open Sans', sans-serif; 
}

body[dir=rtl] .fl-form label.fl-label {
  left: unset;
  right: 0;
}

.fl-form .fl-is-active label.fl-label {
  opacity: 1;
  visibility: visible;
}

.fl-form .fl-has-focus label.fl-label {
  color: #8d8d8d;
}
```
